# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(yellow) {transformation: [0f,0f,0f,-1.2656f,0f,0f,0f,1.2188f,0f,0f,0f,-0.375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blue) {transformation: [0f,0f,0f,-0.9531f,0f,0f,0f,1.75f,0f,0f,0f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(aqua) {transformation: [0f,0f,0f,1.0938f,0f,0f,0f,4.875f,0f,0f,0f,-0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(orange) {transformation: [0f,0f,0f,-0.7941f,0f,0f,0f,0.4688f,0f,0f,0f,-0.1823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(purple) {transformation: [0f,0f,0f,0.9263f,0f,0f,0f,0.7656f,0f,0f,0f,-0.1283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(green) {transformation: [0f,0f,0f,0.6719f,0f,0f,0f,1.8438f,0f,0f,0f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [0f,0f,0f,-0.75f,0f,0f,0f,0.75f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0f,0f,0f,-0.75f,0f,0f,0f,0.75f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0f,0f,0f,-0.75f,0f,0f,0f,0.75f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,0f,0f,-0.75f,0f,0f,0f,0.75f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,0f,0f,-0.75f,0f,0f,0f,0.75f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0f,0f,0f,-0.75f,0f,0f,0f,0.75f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.2246467991473532e-16,"py":0,"pz":1,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] run function ice:flowers/variants/all/apply