# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.078f,0.0254f,-0.0127f,-0.714f,0f,0.037f,0.0742f,0.8578f,0.0284f,-0.0698f,0.0348f,-0.2599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.078f,0.0109f,-0.0262f,-0.6897f,0f,0.0766f,0.0317f,0.9018f,0.0284f,-0.0298f,0.072f,-0.2979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.078f,0.0201f,-0.0201f,-0.6897f,0f,0.0587f,0.0587f,0.9018f,0.0284f,-0.0551f,0.0551f,-0.2979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.0816f,-0.0145f,-0.0031f,-0.6679f,-0.0025f,0.0034f,-0.0829f,0.8944f,0.0146f,0.0816f,0.0029f,-0.2821f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.0818f,0.0041f,-0.0131f,-0.7166f,0.0099f,0.037f,0.0736f,0.8944f,0.0095f,-0.0741f,0.036f,-0.2998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.078f,0.0205f,-0.0196f,-0.6955f,0f,0.0574f,0.0599f,0.8578f,0.0284f,-0.0563f,0.0539f,-0.2531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.350938500309424e-16,"py":0.23750000000000002,"pz":1.103125,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args