# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-0.9397f,-0.262f,0.2198f,0.8164f,0f,0.6428f,0.766f,1.8276f,-0.342f,0.7198f,-0.604f,0.2971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9897f,-0.1291f,0.0622f,0.5234f,-0.0977f,0.9255f,0.3659f,2.3579f,-0.1048f,0.356f,-0.9286f,0.7549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.9397f,-0.2418f,0.2418f,0.5234f,0f,0.7071f,0.7071f,2.3579f,-0.342f,0.6645f,-0.6645f,0.7549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9839f,0.1748f,0.0369f,0.26f,-0.0301f,0.041f,-0.9987f,2.2695f,-0.1761f,-0.9837f,-0.0351f,0.5649f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9862f,-0.0498f,0.158f,0.8473f,0.1195f,0.446f,0.887f,2.2695f,-0.1146f,0.8936f,-0.4339f,0.7787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9397f,-0.2885f,0.1838f,0.5932f,0f,0.5373f,0.8434f,1.8276f,-0.342f,0.7925f,-0.5049f,0.2159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-2.487563810768061e-16,"py":2.375,"pz":2.03125,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args