# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-0.766f,-0.4814f,0.4259f,0.6133f,0f,0.6626f,0.749f,1.9353f,-0.6428f,0.5737f,-0.5076f,0.5146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.923f,-0.246f,0.296f,0.1814f,-0.1309f,0.9239f,0.3596f,2.4657f,-0.362f,0.2932f,-0.8849f,0.8445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.766f,-0.4545f,0.4545f,0.1814f,0f,0.7071f,0.7071f,2.4657f,-0.6428f,0.5417f,-0.5417f,0.8445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.8643f,0.5007f,0.0467f,-0.0012f,-0.0301f,0.041f,-0.9987f,2.3773f,-0.502f,-0.8646f,-0.0204f,0.5759f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.8875f,-0.3524f,0.2968f,0.4776f,0.1196f,0.446f,0.887f,2.3773f,-0.445f,0.8227f,-0.3537f,0.9777f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.766f,-0.5495f,0.3335f,0.4313f,0f,0.5188f,0.8549f,1.9353f,-0.6428f,0.6549f,-0.3974f,0.3619f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-2.6138555119301324e-16,"py":2.6125000000000003,"pz":2.1343750000000004,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args