# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-0.5f,-0.6334f,0.5906f,0.3719f,0f,0.682f,0.7314f,2.0431f,-0.866f,0.3657f,-0.341f,0.6441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.7845f,-0.3289f,0.5257f,-0.1468f,-0.1552f,0.9249f,0.3472f,2.5734f,-0.6004f,0.1908f,-0.7766f,0.8064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.5f,-0.6124f,0.6124f,-0.1468f,0f,0.7071f,0.7071f,2.5734f,-0.866f,0.3536f,-0.3536f,0.8064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.6405f,0.7662f,0.0508f,-0.2265f,-0.0301f,0.041f,-0.9987f,2.485f,-0.7673f,-0.6412f,-0.0032f,0.4916f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.6818f,-0.6126f,0.3999f,0.086f,0.1196f,0.446f,0.887f,2.485f,-0.7217f,0.6526f,-0.2308f,1.0329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.5f,-0.75f,0.433f,0.2531f,0f,0.5f,0.866f,2.0431f,-0.866f,0.433f,-0.25f,0.4384f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-2.7401472130922026e-16,"py":2.85,"pz":2.2375,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args