# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-0.1736f,-0.7024f,0.6903f,0.1208f,0f,0.7009f,0.7133f,2.1509f,-0.9848f,0.1239f,-0.1217f,0.6851f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.5856f,-0.3743f,0.7189f,-0.4221f,-0.18f,0.9249f,0.3349f,2.6812f,-0.7903f,0.0667f,-0.609f,0.6602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.1736f,-0.6964f,0.6964f,-0.4221f,0f,0.7071f,0.7071f,2.6812f,-0.9848f,0.1228f,-0.1228f,0.6602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.3395f,0.9394f,0.0488f,-0.3893f,-0.0301f,0.041f,-0.9987f,2.5928f,-0.9401f,-0.3405f,0.0144f,0.3371f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.3938f,-0.7988f,0.4547f,-0.2808f,0.1196f,0.446f,0.887f,2.5928f,-0.9114f,0.4037f,-0.0801f,0.9527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.1736f,-0.8634f,0.4737f,0.0796f,0f,0.481f,0.8767f,2.1509f,-0.9848f,0.1522f,-0.0835f,0.4512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-2.866438914254274e-16,"py":3.0875,"pz":2.340625,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args