# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.1736f,-0.6841f,0.7084f,-0.1136f,0f,0.7193f,0.6947f,2.2586f,-0.9848f,-0.1206f,0.1249f,0.6445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.3424f,-0.3769f,0.8607f,-0.6153f,-0.2056f,0.9239f,0.3228f,2.789f,-0.9168f,-0.0665f,-0.3938f,0.4355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.1736f,-0.6964f,0.6964f,-0.6153f,0f,0.7071f,0.7071f,2.789f,-0.9848f,-0.1228f,0.1228f,0.4355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.0026f,0.9992f,0.041f,-0.474f,-0.0301f,0.041f,-0.9987f,2.7006f,-0.9995f,0.0013f,0.0302f,0.1431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.0584f,-0.8887f,0.4547f,-0.5825f,0.1196f,0.446f,0.887f,2.7006f,-0.9911f,0.1061f,0.0802f,0.7586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.1736f,-0.8735f,0.4547f,-0.0724f,0f,0.4617f,0.887f,2.2586f,-0.9848f,-0.154f,0.0802f,0.4106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-2.992730615416344e-16,"py":3.3249999999999997,"pz":2.4437499999999996,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args