# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.5f,-0.5851f,0.6385f,-0.3094f,0f,0.7373f,0.6756f,2.3664f,-0.866f,-0.3378f,0.3686f,0.5359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.0433f,-0.3268f,0.9441f,-0.7093f,-0.1839f,0.9262f,0.3291f,2.8967f,-0.982f,-0.1878f,-0.0199f,0.1678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.5f,-0.6124f,0.6124f,-0.7093f,0f,0.7071f,0.7071f,2.8967f,-0.866f,-0.3536f,0.3536f,0.1678f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.3443f,0.9385f,0.0282f,-0.4765f,-0.0301f,0.041f,-0.9987f,2.8083f,-0.9384f,0.343f,0.0424f,-0.0586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.2841f,-0.8714f,0.3999f,-0.789f,0.1196f,0.446f,0.887f,2.8083f,-0.9513f,-0.2042f,0.2309f,0.4827f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.5f,-0.7767f,0.383f,-0.1906f,0f,0.4423f,0.8969f,2.3664f,-0.866f,-0.4484f,0.2211f,0.3302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-3.119022316578415e-16,"py":3.5625,"pz":2.546875,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args