# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.766f,-0.4217f,0.4851f,-0.4501f,0f,0.7547f,0.6561f,2.4741f,-0.6428f,-0.5026f,0.5781f,0.3776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.4255f,-0.2407f,0.8724f,-0.7f,-0.1625f,0.928f,0.3352f,3.0045f,-0.8903f,-0.2844f,0.3558f,-0.1049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.766f,-0.4545f,0.4545f,-0.7f,0f,0.7071f,0.7071f,3.0045f,-0.6428f,-0.5417f,0.5417f,-0.1049f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.6444f,0.7646f,0.012f,-0.4038f,-0.0301f,0.041f,-0.9987f,2.9161f,-0.7641f,0.6433f,0.0495f,-0.2381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.5924f,-0.749f,0.2968f,-0.8825f,0.1196f,0.446f,0.887f,2.9161f,-0.7967f,-0.49f,0.3537f,0.1636f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.766f,-0.5826f,0.2717f,-0.2681f,0f,0.4226f,0.9063f,2.4741f,-0.6428f,-0.6943f,0.3237f,0.225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-3.2453140177404865e-16,"py":3.8000000000000003,"pz":2.6500000000000004,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args