# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.9397f,-0.2176f,0.2639f,-0.5262f,0f,0.7716f,0.6361f,2.5819f,-0.342f,-0.5977f,0.7251f,0.1915f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.7423f,-0.1286f,0.6576f,-0.596f,-0.1414f,0.9293f,0.3413f,3.1122f,-0.655f,-0.3463f,0.6716f,-0.3475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.9397f,-0.2418f,0.2418f,-0.596f,0f,0.7071f,0.7071f,3.1122f,-0.342f,-0.6645f,0.6645f,-0.3475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.8669f,0.4984f,-0.0057f,-0.2721f,-0.0301f,0.041f,-0.9987f,3.0238f,-0.4976f,0.8659f,0.0506f,-0.3713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.8291f,-0.5363f,0.1579f,-0.8594f,0.1196f,0.446f,0.887f,3.0238f,-0.5461f,-0.7166f,0.4339f,-0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.9397f,-0.3131f,0.1377f,-0.303f,0f,0.4027f,0.9153f,2.5819f,-0.342f,-0.8601f,0.3785f,0.1103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-3.3716057189025567e-16,"py":4.0375,"pz":2.753125,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args