# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [1f,0f,0f,-0.5354f,0f,0.788f,0.6157f,2.6897f,0f,-0.6157f,0.788f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.942f,-0.0031f,0.3355f,-0.4167f,-0.1206f,0.93f,0.3473f,3.22f,-0.3131f,-0.3676f,0.8757f,-0.5303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [1f,0f,0f,-0.4167f,0f,0.7071f,0.7071f,3.22f,0f,-0.7071f,0.7071f,-0.5303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.9848f,0.1722f,-0.0226f,-0.1042f,-0.0301f,0.041f,-0.9987f,3.1316f,-0.1711f,0.9842f,0.0456f,-0.4419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.9659f,-0.2589f,-0.0001f,-0.7292f,0.1196f,0.446f,0.887f,3.1316f,-0.2296f,-0.8568f,0.4617f,-0.4419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [1f,0f,0f,-0.2979f,0f,0.3827f,0.9239f,2.6897f,0f,-0.9239f,0.3827f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-3.497897420064628e-16,"py":4.275,"pz":2.85625,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args