# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.9397f,0.2034f,-0.2749f,-0.4825f,0f,0.8039f,0.5948f,2.7974f,0.342f,-0.559f,0.7554f,-0.1756f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.9917f,0.1221f,-0.0406f,-0.1895f,-0.1001f,0.9302f,0.3532f,3.3277f,0.0809f,-0.3462f,0.9347f,-0.6334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.9397f,0.2418f,-0.2418f,-0.1895f,0f,0.7071f,0.7071f,3.3277f,0.342f,-0.6645f,0.6645f,-0.6334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.9839f,-0.1748f,-0.0369f,0.0739f,-0.0301f,0.041f,-0.9987f,3.2394f,0.1761f,0.9838f,0.0351f,-0.4434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.9862f,0.0498f,-0.158f,-0.5134f,0.1196f,0.446f,0.887f,3.2394f,0.1146f,-0.8937f,0.4339f,-0.6572f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.9397f,0.3188f,-0.124f,-0.2593f,0f,0.3624f,0.932f,2.7974f,0.342f,-0.8758f,0.3406f,-0.0944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-3.624189121226698e-16,"py":4.5125,"pz":2.9593749999999996,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args