# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.1896f,0.1404f,-0.0747f,-0.597f,0f,0.1162f,0.2185f,0.9655f,0.1591f,-0.1674f,0.089f,-0.501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.1896f,0.0609f,-0.147f,-0.4902f,0f,0.2286f,0.0947f,1.0968f,0.1591f,-0.0725f,0.1751f,-0.5826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.1896f,0.1125f,-0.1125f,-0.4902f,0f,0.175f,0.175f,1.0968f,0.1591f,-0.134f,0.134f,-0.5826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.2139f,-0.1239f,-0.0115f,-0.445f,-0.0075f,0.0101f,-0.2471f,1.0749f,0.1242f,0.214f,0.005f,-0.5162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.2196f,0.0872f,-0.0734f,-0.5635f,0.0296f,0.1104f,0.2195f,1.0749f,0.1101f,-0.2036f,0.0875f,-0.6156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.1896f,0.1173f,-0.1075f,-0.552f,0f,0.1672f,0.1824f,0.9655f,0.1591f,-0.1398f,0.1281f,-0.4632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.477230201471495e-16,"py":0.47500000000000003,"pz":1.20625,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args