# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.766f,0.3687f,-0.5265f,-0.3782f,0f,0.8192f,0.5736f,2.9052f,0.6428f,-0.4394f,0.6275f,-0.3174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.8824f,0.2335f,-0.4085f,0.0536f,-0.0798f,0.9299f,0.3591f,3.4355f,0.4637f,-0.2843f,0.8391f,-0.6473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.766f,0.4545f,-0.4545f,0.0536f,0f,0.7071f,0.7071f,3.4355f,0.6428f,-0.5417f,0.5417f,-0.6473f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.8644f,-0.5007f,-0.0467f,0.2362f,-0.0301f,0.041f,-0.9987f,3.3471f,0.502f,0.8646f,0.0204f,-0.3787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.8875f,0.3524f,-0.2969f,-0.2426f,0.1196f,0.446f,0.887f,3.3471f,0.445f,-0.8227f,0.3537f,-0.7805f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.766f,0.604f,-0.2198f,-0.1963f,0f,0.342f,0.9397f,2.9052f,0.6428f,-0.7198f,0.262f,-0.1647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-3.7504808223887693e-16,"py":4.75,"pz":3.0625,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args