# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.2181f,0.3288f,-0.186f,-0.4009f,0f,0.2148f,0.3796f,1.0733f,0.3777f,-0.1898f,0.1074f,-0.6944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.2181f,0.1445f,-0.349f,-0.1747f,0f,0.403f,0.1669f,1.3046f,0.3777f,-0.0835f,0.2015f,-0.7652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.2181f,0.2671f,-0.2671f,-0.1747f,0f,0.3084f,0.3084f,1.3046f,0.3777f,-0.1542f,0.1542f,-0.7652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.2794f,-0.3342f,-0.0222f,-0.1399f,-0.0132f,0.0179f,-0.4356f,1.266f,0.3347f,0.2797f,0.0014f,-0.6279f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.2974f,0.2672f,-0.1744f,-0.2762f,0.0521f,0.1945f,0.3869f,1.266f,0.3148f,-0.2846f,0.1007f,-0.8639f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.2181f,0.284f,-0.249f,-0.3491f,0f,0.2876f,0.3279f,1.0733f,0.3777f,-0.164f,0.1438f,-0.6047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.6035219026335656e-16,"py":0.7125,"pz":1.309375,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args