# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [0.1083f,0.5264f,-0.3163f,-0.1431f,0f,0.3212f,0.5345f,1.181f,0.6141f,-0.0928f,0.0558f,-0.8115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.1083f,0.235f,-0.5673f,0.1954f,0f,0.5761f,0.2386f,1.5117f,0.6141f,-0.0414f,0.1f,-0.796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [0.1083f,0.4342f,-0.4342f,0.1954f,0f,0.4409f,0.4409f,1.5117f,0.6141f,-0.0766f,0.0766f,-0.796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0.2117f,-0.5857f,-0.0304f,0.175f,-0.0188f,0.0256f,-0.6227f,1.4566f,0.5862f,0.2123f,-0.009f,-0.5946f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.2456f,0.4981f,-0.2836f,0.1073f,0.0745f,0.2781f,0.5531f,1.4566f,0.5683f,-0.2517f,0.05f,-0.9784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [0.1083f,0.4704f,-0.3947f,-0.1174f,0f,0.4008f,0.4777f,1.181f,0.6141f,-0.0829f,0.0696f,-0.6657f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.7298136037956366e-16,"py":0.9500000000000001,"pz":1.4125,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args