# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-0.1379f,0.6596f,-0.4202f,0.1466f,0f,0.4267f,0.6697f,1.2888f,0.782f,0.1163f,-0.0741f,-0.8315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.1379f,0.2993f,-0.7225f,0.545f,0f,0.7337f,0.3039f,1.7099f,0.782f,0.0528f,-0.1274f,-0.6655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.1379f,0.553f,-0.553f,0.545f,0f,0.5615f,0.5615f,1.7099f,0.782f,0.0975f,-0.0975f,-0.6655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.0021f,-0.7934f,-0.0325f,0.4328f,-0.0239f,0.0326f,-0.7931f,1.6397f,0.7937f,-0.0011f,-0.024f,-0.4333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0.0463f,0.7057f,-0.3611f,0.5189f,0.0949f,0.3542f,0.7044f,1.6397f,0.7871f,-0.0843f,-0.0637f,-0.9221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.1379f,0.6099f,-0.4895f,0.1139f,0f,0.4971f,0.6193f,1.2888f,0.782f,0.1075f,-0.0863f,-0.6457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.8561053049577073e-16,"py":1.1875,"pz":1.515625,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args