# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-0.468f,0.6721f,-0.4533f,0.4306f,0f,0.5234f,0.776f,1.3966f,0.8107f,0.388f,-0.2617f,-0.7458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.468f,0.3102f,-0.749f,0.8049f,0f,0.8648f,0.3582f,1.893f,0.8107f,0.1791f,-0.4324f,-0.4013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.468f,0.5732f,-0.5732f,0.8049f,0f,0.6619f,0.6619f,1.893f,0.8107f,0.331f,-0.331f,-0.4013f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.3223f,-0.8785f,-0.0263f,0.587f,-0.0282f,0.0384f,-0.9349f,1.8102f,0.8784f,-0.3211f,-0.0397f,-0.1893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.266f,0.8157f,-0.3743f,0.8795f,0.1119f,0.4175f,0.8303f,1.8102f,0.8905f,0.1912f,-0.2161f,-0.696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.468f,0.6431f,-0.4935f,0.3194f,0f,0.5698f,0.7426f,1.3966f,0.8107f,0.3713f,-0.2849f,-0.5533f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.9823970061197778e-16,"py":1.425,"pz":1.61875,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args