# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-0.7959f,0.5437f,-0.3878f,0.669f,0f,0.6033f,0.8459f,1.5043f,0.6678f,0.648f,-0.4622f,-0.5614f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.7959f,0.2556f,-0.617f,0.9287f,0f,0.9599f,0.3976f,2.0553f,0.6678f,0.3046f,-0.7353f,-0.06f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-0.7959f,0.4722f,-0.4722f,0.9287f,0f,0.7347f,0.7347f,2.0553f,0.6678f,0.5628f,-0.5628f,-0.06f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.6696f,-0.7943f,-0.0124f,0.621f,-0.0313f,0.0426f,-1.0376f,1.9635f,0.7938f,-0.6683f,-0.0514f,0.0784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.6155f,0.7782f,-0.3084f,1.1184f,0.1242f,0.4634f,0.9216f,1.9635f,0.8278f,0.5091f,-0.3675f,-0.339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.7959f,0.5386f,-0.3949f,0.48f,0f,0.6144f,0.8379f,1.5043f,0.6678f,0.6419f,-0.4706f,-0.4028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-2.1086887072818485e-16,"py":1.6624999999999999,"pz":1.7218749999999998,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args