# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-1.0263f,0.2983f,-0.2248f,0.8266f,0f,0.6573f,0.8722f,1.6121f,0.3735f,0.8196f,-0.6176f,-0.3009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9921f,0.1423f,-0.4341f,0.9029f,-0.0354f,1.0108f,0.4121f,2.1913f,0.4554f,0.3884f,-0.9136f,0.2878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1.0263f,0.2641f,-0.2641f,0.9029f,0f,0.7723f,0.7723f,2.1913f,0.3735f,0.7257f,-0.7257f,0.2878f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9468f,-0.5444f,0.0062f,0.5491f,-0.0329f,0.0448f,-1.0908f,2.0947f,0.5434f,-0.9458f,-0.0552f,0.3138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9056f,0.5857f,-0.1725f,1.1906f,0.1306f,0.4871f,0.9688f,2.0947f,0.5964f,0.7826f,-0.4739f,0.0803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0263f,0.306f,-0.2143f,0.5829f,0f,0.6264f,0.8947f,1.6121f,0.3735f,0.8407f,-0.5887f,-0.2122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-2.2349804084439197e-16,"py":1.9000000000000001,"pz":1.8250000000000002,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args