# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(left_leg) {transformation: [-1.0839f,0f,0f,0.8787f,0f,0.6747f,0.8483f,1.7198f,0f,0.8483f,-0.6747f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1.0674f,0.0009f,-0.1886f,0.75f,-0.0704f,1.0037f,0.4029f,2.2946f,0.175f,0.409f,-0.9884f,0.5748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(body) {transformation: [-1.0839f,0f,0f,0.75f,0f,0.7664f,0.7664f,2.2946f,0f,0.7664f,-0.7664f,0.5748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-1.0674f,-0.1866f,0.0246f,0.4113f,-0.0327f,0.0445f,-1.0825f,2.1988f,0.1854f,-1.0668f,-0.0494f,0.479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-1.047f,0.2806f,0f,1.0887f,0.1296f,0.4834f,0.9614f,2.1988f,0.2488f,0.9287f,-0.5005f,0.479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1.0839f,0f,0f,0.6213f,0f,0.6022f,0.9012f,1.7198f,0f,0.9012f,-0.6022f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-2.3612721096059904e-16,"py":2.1375,"pz":1.928125,"ry":182.5,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args