# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ice:flowers/root/on_tick/transform_locators
function ice:flowers/root/on_tick/select_camera_camera1 with storage animated_java:temp entry.data.cameras.camera1