# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=ice.flowers.animation.powerup.playing] run function ice:flowers/animations/powerup/zzz/on_tick
function ice:flowers/root/on_tick/transform_floating_entities
execute on passengers run tp @s ~ ~ ~ ~ ~