# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=ice.flowers.root] run return run tellraw @a [{"text":"","color":"red"},[{"color":"gray","text":"\n "},{"color":"#00aced","text":"ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ"},{"color":"dark_gray","italic":true,"text":"\n (ice:flowers)"},"\n → "],"ᴇʀʀᴏʀ: ",{"text":"Function Not Executed as Root Entity","underlined":true},"\n\n ",{"text":"[This Function]","color":"yellow","hoverEvent":{"action":"show_text","contents":[{"color":"yellow","text":"ice:flowers/variants/green/apply"}]}}," must be executed as the rig's root entity.",{"text":"\n\n ≡ ","color":"white","extra":[{"text":"ꜱʜᴏᴡ ᴇxᴀᴍᴘʟᴇ ᴄᴏᴍᴍᴀɴᴅ","color":"aqua","underlined":true,"clickEvent":{"action":"suggest_command","value":"/execute as @e[tag=ice.flowers.root] run function ice:flowers/variants/green/apply"}}]},["\n\n ",{"italic":true,"underlined":true,"color":"blue","text":"▶ Learn More ◀","clickEvent":{"action":"open_url","value":"https://animated-java.dev/docs/core-concepts/tags#practical-selector-examples"}}],"\n"]
execute on passengers if entity @s[tag=ice.flowers.node.yellow] at @s run function ice:flowers/variants/green/zzz/apply_to_node_yellow
execute on passengers if entity @s[tag=ice.flowers.node.blue] at @s run function ice:flowers/variants/green/zzz/apply_to_node_blue
execute on passengers if entity @s[tag=ice.flowers.node.aqua] at @s run function ice:flowers/variants/green/zzz/apply_to_node_aqua
execute on passengers if entity @s[tag=ice.flowers.node.orange] at @s run function ice:flowers/variants/green/zzz/apply_to_node_orange
execute on passengers if entity @s[tag=ice.flowers.node.purple] at @s run function ice:flowers/variants/green/zzz/apply_to_node_purple
execute on passengers if entity @s[tag=ice.flowers.node.green] at @s run function ice:flowers/variants/green/zzz/apply_to_node_green
execute on passengers if entity @s[tag=ice.flowers.node.left_leg] at @s run function ice:flowers/variants/green/zzz/apply_to_node_left_leg
execute on passengers if entity @s[tag=ice.flowers.node.head] at @s run function ice:flowers/variants/green/zzz/apply_to_node_head
execute on passengers if entity @s[tag=ice.flowers.node.body] at @s run function ice:flowers/variants/green/zzz/apply_to_node_body
execute on passengers if entity @s[tag=ice.flowers.node.right_arm] at @s run function ice:flowers/variants/green/zzz/apply_to_node_right_arm
execute on passengers if entity @s[tag=ice.flowers.node.left_arm] at @s run function ice:flowers/variants/green/zzz/apply_to_node_left_arm
execute on passengers if entity @s[tag=ice.flowers.node.right_leg] at @s run function ice:flowers/variants/green/zzz/apply_to_node_right_leg
return 1