# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=ice.flowers.root] run return run tellraw @a [{"text":"","color":"red"},[{"color":"gray","text":"\n "},{"color":"#00aced","text":"ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ"},{"color":"dark_gray","italic":true,"text":"\n (ice:flowers)"},"\n → "],"ᴇʀʀᴏʀ: ",{"text":"Function Not Executed as Root Entity","underlined":true},"\n\n ",{"text":"[This Function]","color":"yellow","hoverEvent":{"action":"show_text","contents":[{"color":"yellow","text":"ice:flowers/animations/powerup/tween"}]}}," must be executed as the rig's root entity.",{"text":"\n\n ≡ ","color":"white","extra":[{"text":"ꜱʜᴏᴡ ᴇxᴀᴍᴘʟᴇ ᴄᴏᴍᴍᴀɴᴅ","color":"aqua","underlined":true,"clickEvent":{"action":"suggest_command","value":"/execute as @e[tag=ice.flowers.root] run function ice:flowers/animations/powerup/tween"}}]},["\n\n ",{"italic":true,"underlined":true,"color":"blue","text":"▶ Learn More ◀","clickEvent":{"action":"open_url","value":"https://animated-java.dev/docs/core-concepts/tags#practical-selector-examples"}}],"\n"]
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function ice:flowers/animations/pause_all
tag @s add ice.flowers.animation.powerup.playing
$scoreboard players set @s aj.tween_duration $(duration)
$scoreboard players set @s aj.powerup.frame $(to_frame)
scoreboard players operation #this aj.i = @s aj.tween_duration
tag @s add aj.transforms_only
execute at @s run function ice:flowers/animations/powerup/zzz/apply_frame {frame: 0}
$execute at @s run function ice:flowers/animations/powerup/zzz/apply_frame {frame: $(to_frame)}
tag @s remove aj.transforms_only
execute on passengers store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i