# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "ice:flowers"
data modify storage animated_java:temp entry.data.rig_hash set value "29b58cdb98e58b59a267740c8efc25734eace67f845ce7b7838eba17570bfb79"
tp @s ~ ~ ~ ~ ~
summon minecraft:item_display ^0 ^0 ^0 {Tags:["","aj.global.camera","aj.global.entity","aj.global.node","aj.global.node.camera1","aj.global.root.child","aj.global.root.child.camera","aj.new","ice.flowers.camera","ice.flowers.camera.camera1","ice.flowers.entity","ice.flowers.node","ice.flowers.node.camera1"], teleport_duration: 2}
execute as @n[ type=minecraft:item_display, tag=ice.flowers.camera.camera1, tag=aj.new, distance=..7 ] run function ice:flowers/zzz/summon/as_camera/camera1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.camera1 set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.cameras.camera1.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.yellow] run function ice:flowers/zzz/summon/as_node/yellow
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.yellow set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.blue] run function ice:flowers/zzz/summon/as_node/blue
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.blue set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.aqua] run function ice:flowers/zzz/summon/as_node/aqua
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.aqua set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.orange] run function ice:flowers/zzz/summon/as_node/orange
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.orange set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.purple] run function ice:flowers/zzz/summon/as_node/purple
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.purple set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.green] run function ice:flowers/zzz/summon/as_node/green
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.green set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.left_leg] run function ice:flowers/zzz/summon/as_node/left_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_leg set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.head] run function ice:flowers/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.body] run function ice:flowers/zzz/summon/as_node/body
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.body set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.right_arm] run function ice:flowers/zzz/summon/as_node/right_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.left_arm] run function ice:flowers/zzz/summon/as_node/left_arm
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.left_arm set from storage animated_java:gu out
execute on passengers if entity @s[tag=ice.flowers.node.right_leg] run function ice:flowers/zzz/summon/as_node/right_leg
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.right_leg set from storage animated_java:gu out
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function ice:flowers/zzz/set_default_pose
execute if data storage animated_java:temp args.variant run function ice:flowers/zzz/summon/variant_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function ice:flowers/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run tp @s ~ ~ ~ ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new