# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function ice:flowers/zzz/reset_floating_entities
execute on passengers if entity @s[tag=ice.flowers.node.yellow] run data merge entity @s { transformation: [-1.2917f,0f,0f,-1.2656f,0f,1.2917f,0f,1.2188f,0f,0f,-1.2917f,-0.375f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.blue] run data merge entity @s { transformation: [-1.3333f,0f,0f,-0.9531f,0f,1.3333f,0f,1.75f,0f,0f,-1.3333f,-0.75f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.aqua] run data merge entity @s { transformation: [-1f,0f,0f,1.0938f,0f,1f,0f,1.75f,0f,0f,-1f,-0.1875f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.orange] run data merge entity @s { transformation: [-1f,0f,0f,-0.7941f,0f,1f,0f,0.4688f,0f,0f,-1f,-0.1823f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.purple] run data merge entity @s { transformation: [-1f,0f,0f,0.9263f,0f,1f,0f,0.7656f,0f,0f,-1f,-0.1283f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.green] run data merge entity @s { transformation: [-1.0417f,0f,0f,0.6719f,0f,1.0417f,0f,1.8438f,0f,0f,-1.0417f,-0.75f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.left_leg] run data merge entity @s { transformation: [-1f,0f,0f,0.1188f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.right_arm] run data merge entity @s { transformation: [-1f,0f,0f,-0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.left_arm] run data merge entity @s { transformation: [-1f,0f,0f,0.3125f,0f,1f,0f,1.375f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=ice.flowers.node.right_leg] run data merge entity @s { transformation: [-1f,0f,0f,-0.1187f,0f,1f,0f,0.75f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }