# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage ice:flowers rig_hash set value '29b58cdb98e58b59a267740c8efc25734eace67f845ce7b7838eba17570bfb79'
scoreboard objectives add aj.powerup.frame dummy